# Generated by Django 2.1 on 2018-08-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='integer',
            field=models.IntegerField(default=34),
        ),
    ]
